apiVersion: v1
kind: Service
metadata:
  name: medical-chatbot-service
  labels:
    app: medical-chatbot
spec:
  selector:
    app: medical-chatbot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
